### ISSUE TITLE
deposit_to_paraclear

### ISSUE THREAD

**Issue by viponedream** [tradeparadex/code-samples#25]
deposit_to_paraclear

starknet_py.net.client_errors.ClientError: Client failed with code 400: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Contract with address 0xxxx is not deployed."}.

**Comment by amayvs** [comment]
@viponedream The account needs to be onboarded before you can deposit to Paraclear

Please refer to docs for more info - [Onboarding & Wallets](https://docs.paradex.trade/introduction/onboarding-and-wallets)
