### ISSUE TITLE
Mainnet config missing from Python SDK

### ISSUE THREAD

**Issue by t0mm4rx** [tradeparadex/code-samples#57]
Hey,

I had to add the mainnet chain ID to get it to work in production. Otherwise, it was failing to sign orders.

In `starknet_utils.py`:
```
class CustomStarknetChainId(Enum):
    PRIVATE_SN_TESTNET = int_from_bytes(b"PRIVATE_SN_POTC_SEPOLIA")
    # I added this line
    PRIVATE_SN_PARACLEAR_MAINNET = int_from_bytes(b"PRIVATE_SN_PARACLEAR_MAINNET")
```

**Comment by amayvs** [comment]
@t0mm4rx Could you give our new python SDK a try?

---

🐍 **Paradex Python SDK**

Features available in v0.1.0
- Automatic account generation with L1 or L2 private key
- Automatic onboarding and auth calls with signatures and jwt token retrieval
- Calls to public and private REST API endpoints
- Connect to WebSocket API channels

📦 https://pypi.org/project/paradex_py/
📖 https://tradeparadex.github.io/paradex-py/

_Note: Experimental SDK, library API is subject to change_

---
